# Generated by Django 3.2.6 on 2021-08-30 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WebService', '0004_auto_20210830_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to='WebService.usuarios')),
            ],
            options={
                'db_table': 'sesiones',
            },
        ),
    ]
