# Generated by Django 3.0.8 on 2021-08-24 16:57

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('ruta_foto', models.ImageField(blank=True, null=True, upload_to='perfil')),
                ('genero', models.CharField(max_length=1)),
                ('celular', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'familiares',
            },
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre1', models.CharField(max_length=20)),
                ('nombre2', models.CharField(max_length=20)),
                ('apellido1', models.CharField(max_length=20)),
                ('apellido2', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('ruta_foto', models.ImageField(blank=True, null=True, upload_to='perfil')),
                ('genero', models.CharField(max_length=1)),
                ('correo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pacientes',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_usuario', models.CharField(max_length=25, unique=True)),
                ('clave', fernet_fields.fields.EncryptedTextField()),
                ('tipo_cuenta', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('msj_sms', models.CharField(max_length=400)),
                ('familiar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SMS', to='WebService.Familiares')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SMS', to='WebService.Pacientes')),
            ],
            options={
                'db_table': 'sms',
            },
        ),
        migrations.CreateModel(
            name='SaludCardiaca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salud_cardiaca', to='WebService.Pacientes')),
            ],
            options={
                'db_table': 'salud_cardiaca',
            },
        ),
        migrations.AddField(
            model_name='pacientes',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='paciente', to='WebService.Usuarios'),
        ),
        migrations.AddField(
            model_name='familiares',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='familiares', to='WebService.Pacientes'),
        ),
        migrations.AddField(
            model_name='familiares',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='familiar', to='WebService.Usuarios'),
        ),
        migrations.CreateModel(
            name='BPM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpm', models.CharField(max_length=3)),
                ('hora', models.DateTimeField()),
                ('salud_cardiaca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BPM', to='WebService.SaludCardiaca')),
            ],
            options={
                'db_table': 'bpm',
            },
        ),
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('msj_alerta', models.CharField(max_length=400)),
                ('familiar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='WebService.Familiares')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='WebService.Pacientes')),
            ],
            options={
                'db_table': 'alertas',
            },
        ),
    ]
