# Generated by Django 3.0.8 on 2021-08-22 14:07

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WebService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertas',
            name='familiar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='WebService.Familiares'),
        ),
        migrations.AlterField(
            model_name='alertas',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='WebService.Pacientes'),
        ),
        migrations.AlterField(
            model_name='familiares',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='familiares', to='WebService.Pacientes'),
        ),
        migrations.AlterField(
            model_name='familiares',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='familiar', to='WebService.Usuarios'),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='paciente', to='WebService.Usuarios'),
        ),
        migrations.AlterField(
            model_name='saludcardiaca',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salud_cardiaca', to='WebService.Pacientes'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='clave',
            field=fernet_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table='usuarios',
        ),
    ]
