# Generated by Django 3.0.8 on 2021-08-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebService', '0002_auto_20210822_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='usuario',
            new_name='nom_usuario',
        ),
    ]
