# Generated by Django 3.2.6 on 2021-08-30 01:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WebService', '0003_auto_20210830_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='saludcardiaca',
            name='bpm',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='saludcardiaca',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BPM',
        ),
    ]
